import type { Paper } from "@/types/paper";

export const papers: Paper[] = [
  {
    slug: "pointer-architecture",
    title:
      "Pointer Architecture: A Constrained Information-Geometric Model of Galactic Rotation Curves",
    authors: ["Mikhail Savchenko"],
    year: 2026,
    status: "preprint",
    venue: "arXiv pending · Zenodo DOI",
    abstract:
      "We compare three information-geometric models of galactic rotation on the 171-galaxy SPARC sample: unconstrained pointer, constrained pointer (with a physical prior on halo extent), and a standard NFW baseline. The constrained pointer wins AIC on 60 of 171 galaxies and shows a positive partial correlation between halo extent and inferred information mass (ρ = +0.19, q_FDR = 0.04). Four of six residual-structure features correlate with galactic age at FDR-controlled significance. A full reproducibility pipeline — code, data, and fit diagnostics — is released alongside the preprint.",
    tldr: [
      "3-model head-to-head on 171 SPARC galaxies",
      "Constrained Pointer wins AIC on 60/171",
      "Partial correlation on halo extent: ρ = +0.19, q_FDR = 0.04",
      "4 of 6 residual-structure features correlate with galactic age",
      "Full reproducibility pipeline released (code + data + fit diagnostics)",
    ],
    predictions: [
      "Constrained pointer fit quality improves systematically with galactic age.",
      "Residual-structure features at large radii should track halo concentration, not stellar mass.",
      "Low-surface-brightness galaxies should show larger pointer-vs-NFW AIC gaps.",
      "Independent samples (LITTLE THINGS, THINGS) should reproduce the ρ direction on halo extent.",
      "Falsifier: if the ρ sign flips on an independent age-controlled resample, the model fails.",
      "Falsifier: if AIC-preferred galaxies correlate with survey artefacts rather than age, the result is observational.",
      "Falsifier: if reproducibility pipeline yields materially different fits under reasonable re-parameterisation, results are over-fit.",
    ],
    pdfPath: "/pdfs/pointer-architecture-v2.pdf",
    codeUrl: "https://github.com/neuralcosmology/pointer-architecture",
    companionBookSlug: "celestial-code",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    references: [
      {
        id: "lelli2016sparc",
        authors: "Lelli F., McGaugh S. S., Schombert J. M.",
        year: 2016,
        title: "SPARC: Mass models for 175 disk galaxies with Spitzer photometry and accurate rotation curves",
        venue: "The Astronomical Journal 152, 157",
        doi: "10.3847/0004-6256/152/6/157",
      },
      {
        id: "navarro1996structure",
        authors: "Navarro J. F., Frenk C. S., White S. D. M.",
        year: 1996,
        title: "The structure of cold dark-matter halos",
        venue: "The Astrophysical Journal 462, 563",
        doi: "10.1086/177173",
      },
      {
        id: "milgrom1983modification",
        authors: "Milgrom M.",
        year: 1983,
        title: "A modification of the Newtonian dynamics as a possible alternative to the hidden mass hypothesis",
        venue: "The Astrophysical Journal 270, 365",
        doi: "10.1086/161130",
      },
      {
        id: "mcgaugh2016radial",
        authors: "McGaugh S. S., Lelli F., Schombert J. M.",
        year: 2016,
        title: "Radial acceleration relation in rotationally supported galaxies",
        venue: "Physical Review Letters 117, 201101",
        doi: "10.1103/PhysRevLett.117.201101",
      },
      {
        id: "li2020comprehensive",
        authors: "Li P., Lelli F., McGaugh S., Schombert J.",
        year: 2020,
        title: "A comprehensive catalog of dark-matter halo models for SPARC galaxies",
        venue: "The Astrophysical Journal Supplement 247, 31",
        doi: "10.3847/1538-4365/ab700e",
      },
      {
        id: "kamada2017self",
        authors: "Kamada A., Kaplinghat M., Pace A. B., Yu H.-B.",
        year: 2017,
        title: "Self-interacting dark matter can explain diverse galactic rotation curves",
        venue: "Physical Review Letters 119, 111102",
        doi: "10.1103/PhysRevLett.119.111102",
      },
      {
        id: "salucci2019distribution",
        authors: "Salucci P.",
        year: 2019,
        title: "The distribution of dark matter in galaxies",
        venue: "The Astronomy and Astrophysics Review 27, 2",
        doi: "10.1007/s00159-018-0113-1",
      },
      {
        id: "rubin1970rotation",
        authors: "Rubin V. C., Ford W. K.",
        year: 1970,
        title: "Rotation of the Andromeda Nebula from a spectroscopic survey of emission regions",
        venue: "The Astrophysical Journal 159, 379",
        doi: "10.1086/150317",
      },
      {
        id: "verlinde2011origin",
        authors: "Verlinde E.",
        year: 2011,
        title: "On the origin of gravity and the laws of Newton",
        venue: "Journal of High Energy Physics 2011(4), 29",
        doi: "10.1007/JHEP04(2011)029",
      },
      {
        id: "verlinde2017emergent",
        authors: "Verlinde E.",
        year: 2017,
        title: "Emergent gravity and the dark universe",
        venue: "SciPost Physics 2(3), 016",
        doi: "10.21468/SciPostPhys.2.3.016",
      },
      {
        id: "vanchurin2020world",
        authors: "Vanchurin V.",
        year: 2020,
        title: "The world as a neural network",
        venue: "Entropy 22(11), 1210",
        doi: "10.3390/e22111210",
      },
      {
        id: "wolfram2020project",
        authors: "Wolfram S.",
        year: 2020,
        title: "A class of models with the potential to represent fundamental physics",
        venue: "Complex Systems 29(2), 107",
      },
      {
        id: "gorard2020some",
        authors: "Gorard J.",
        year: 2020,
        title: "Some relativistic and gravitational properties of the Wolfram model",
        venue: "arXiv",
        arxiv: "2004.14810",
      },
      {
        id: "tononi2004iit",
        authors: "Tononi G.",
        year: 2004,
        title: "An information integration theory of consciousness",
        venue: "BMC Neuroscience 5, 42",
        doi: "10.1186/1471-2202-5-42",
      },
      {
        id: "tononi2008",
        authors: "Tononi G.",
        year: 2008,
        title: "Consciousness as integrated information",
        venue: "Biological Bulletin 215, 216",
        doi: "10.2307/25470707",
      },
      {
        id: "penrose1996orchestrated",
        authors: "Penrose R., Hameroff S.",
        year: 1996,
        title: "Orchestrated reduction of quantum coherence in brain microtubules",
        venue: "Mathematics and Computers in Simulation 40, 453",
        doi: "10.1016/0378-4754(96)80476-9",
      },
      {
        id: "chalmers1995facing",
        authors: "Chalmers D. J.",
        year: 1995,
        title: "Facing up to the problem of consciousness",
        venue: "Journal of Consciousness Studies 2(3), 200",
      },
      {
        id: "dehaene2003",
        authors: "Dehaene S., Sergent C., Changeux J.-P.",
        year: 2003,
        title: "A neuronal network model linking subjective reports and objective physiological data",
        venue: "PNAS 100(14), 8520",
        doi: "10.1073/pnas.1332574100",
      },
      {
        id: "baars1988cognitive",
        authors: "Baars B. J.",
        year: 1988,
        title: "A Cognitive Theory of Consciousness",
        venue: "Cambridge University Press",
      },
      {
        id: "libet1983time",
        authors: "Libet B.",
        year: 1983,
        title: "Time of conscious intention to act in relation to onset of cerebral activity",
        venue: "Brain 106(3), 623",
        doi: "10.1093/brain/106.3.623",
      },
      {
        id: "rosenthal2005",
        authors: "Rosenthal D. M.",
        year: 2005,
        title: "Consciousness and Mind",
        venue: "Oxford University Press",
      },
      {
        id: "miller1956magical",
        authors: "Miller G. A.",
        year: 1956,
        title: "The magical number seven, plus or minus two",
        venue: "Psychological Review 63, 81",
        doi: "10.1037/h0043158",
      },
      {
        id: "wheeler1990information",
        authors: "Wheeler J. A.",
        year: 1990,
        title: "Information, physics, quantum: the search for links",
        venue: "Complexity, Entropy, and the Physics of Information (Addison-Wesley)",
      },
      {
        id: "bekenstein1973black",
        authors: "Bekenstein J. D.",
        year: 1973,
        title: "Black holes and entropy",
        venue: "Physical Review D 7(8), 2333",
        doi: "10.1103/PhysRevD.7.2333",
      },
      {
        id: "susskind1995world",
        authors: "Susskind L.",
        year: 1995,
        title: "The world as a hologram",
        venue: "Journal of Mathematical Physics 36, 6377",
        doi: "10.1063/1.531249",
      },
      {
        id: "thooft1993dimensional",
        authors: "'t Hooft G.",
        year: 1993,
        title: "Dimensional reduction in quantum gravity",
        venue: "arXiv",
        arxiv: "gr-qc/9310026",
      },
      {
        id: "maldacena2013cool",
        authors: "Maldacena J., Susskind L.",
        year: 2013,
        title: "Cool horizons for entangled black holes",
        venue: "Fortschritte der Physik 61, 781",
        doi: "10.1002/prop.201300020",
      },
      {
        id: "page1993information",
        authors: "Page D. N.",
        year: 1993,
        title: "Information in black-hole radiation",
        venue: "Physical Review Letters 71, 3743",
        doi: "10.1103/PhysRevLett.71.3743",
      },
      {
        id: "godel1931formally",
        authors: "Gödel K.",
        year: 1931,
        title: "Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme I",
        venue: "Monatshefte für Mathematik und Physik 38, 173",
      },
      {
        id: "turing1936computable",
        authors: "Turing A. M.",
        year: 1936,
        title: "On computable numbers, with an application to the Entscheidungsproblem",
        venue: "Proc. London Math. Soc. 42, 230",
      },
      {
        id: "chaitin1975theory",
        authors: "Chaitin G. J.",
        year: 1975,
        title: "A theory of program size formally identical to information theory",
        venue: "Journal of the ACM 22(3), 329",
        doi: "10.1145/321892.321894",
      },
      {
        id: "kung1981optimistic",
        authors: "Kung H. T., Robinson J. T.",
        year: 1981,
        title: "On optimistic methods for concurrency control",
        venue: "ACM Transactions on Database Systems 6(2), 213",
        doi: "10.1145/319566.319567",
      },
    ],
    dataset: {
      name: "Pointer Architecture — SPARC fit outputs and residual diagnostics (v2)",
      description:
        "Per-galaxy fit outputs for the Pointer, NFW, and Burkert halo models on the 171-galaxy SPARC sample, plus derived observables (M_halo, M_bar, f_DM), composite galactic age, partial correlations, PCA, and structural residual features. Four-stage reproducibility pipeline; deterministic differential-evolution + Sobol init.",
      distributions: [
        {
          name: "final_fits.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/final_fits.csv",
          format: "text/csv",
        },
        {
          name: "final_corr.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/final_corr.csv",
          format: "text/csv",
        },
        {
          name: "final_pca.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/final_pca.csv",
          format: "text/csv",
        },
        {
          name: "phase2_derived.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/phase2_derived.csv",
          format: "text/csv",
        },
        {
          name: "phase3_constrained.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/phase3_constrained.csv",
          format: "text/csv",
        },
        {
          name: "phase4_residuals.csv",
          url: "https://github.com/neuralcosmology/pointer-architecture/blob/main/code/phase4_residuals.csv",
          format: "text/csv",
        },
      ],
      license: "CC-BY-4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      version: "v2",
      keywords: [
        "galactic rotation curves",
        "SPARC",
        "dark matter halo",
        "NFW",
        "Burkert",
        "information geometry",
        "AIC",
        "BIC",
        "reproducibility",
      ],
    },
  },
];

export function getPaperBySlug(slug: string): Paper | undefined {
  return papers.find((p) => p.slug === slug);
}
