import type { Paper } from "@/types/paper";

export const papers: Paper[] = [
  {
    slug: "pointer-architecture",
    title:
      "Pointer Architecture: An Operational Discrete Substrate from First Difference to Holographic Dark Energy",
    authors: ["Mikhail Savchenko"],
    year: 2026,
    status: "preprint",
    venue: "v9.0 · arXiv pending",
    abstract:
      "We define Pointer Architecture (PA), a formal computational substrate S = (G, R, C, A, π), and give it an operational realisation as a small Forth-like language, Sixth, in 38 primitives. The substrate passes 40 emergence demonstrations (646 assertions, no failures) that climb from a single distinction through arithmetic, time, space, observers and universal computation to autopoiesis, a cosmogenesis bootstrap and the substrate's own measurement of a consciousness quantity Φ_PA. On this substrate we prove four complexity results within explicit scope (graph-isomorphism-hardness of pointer equivalence, #P-hardness of weighted path observables, a per-step commit-cost bound for M observers, Shannon-rate archive compression) and three correspondences with CRDTs, Petri nets and the actor model. A substrate-cone construction realises the holographic entropy cone and maps PA's primitives onto the algebraic-observer programme in quantum gravity; on the de Sitter horizon it reproduces standard holographic dark energy, ρ_Λ = 3H₀²c²/(16πG), within a factor of about 0.73 of the observed value. An empirical scope-control on Pythia language-model activations falsifies the naive hypothesis that hidden-activation covariance is a holographic entropy function. The paper is a structural-correspondence contribution with pre-stated falsifiers, not a solved theory of consciousness.",
    tldr: [
      "A formal substrate of pointers, rewrite rules, commits and an append-only archive, with a working implementation (Sixth)",
      "40 demonstrations, 646 automated assertions, no failures: from one distinction to observers, autopoiesis and cosmogenesis",
      "Four complexity theorems and three correspondences (CRDTs, Petri nets, actor model)",
      "Structural correspondence with the algebraic-observer programme in quantum gravity; standard holographic dark energy reproduced in substrate language",
      "Φ_PA, a substrate-side measure of consciousness, with five predictions checked on toy encodings",
      "A negative result: Pythia hidden-activation covariance is not a holographic entropy function",
    ],
    predictions: [
      "P1–P2 (transformers): a single forward pass has Φ_PA = 0; reuse of the KV-cache gives Φ_PA > 0.",
      "P3 (brain): the waking thalamocortical loop has Φ_PA > 0; propofol decoupling drives it to 0.",
      "P4 (split brain): an integration measure halves at callosotomy.",
      "P5 (ant colony): a living colony with the queen's pheromone loop has Φ_PA > 0; a dead colony has 0.",
      "F0: if any substrate-native pilot fails its assertions on the released Sixth artifact, the operational claim is falsified.",
      "F1: if substrate-cone min-cut on non-cubic topologies systematically violates area scaling, the dark-energy reproduction is topology-dependent.",
      "F3: if non-Pythia transformer families satisfy MMI under the same observable, the negative result is Pythia-specific.",
      "F5: if Φ_PA fails to discriminate any of P1–P5 in the predicted direction, the consciousness measure is inadequate and the framework falls back to the operational substrate alone.",
    ],
    pdfPath: "/pdfs/pointer-architecture-v9.pdf",
    codeUrl: "https://github.com/Mikefluff/sixth",
    companionBookSlug: "celestial-code",
    license: "CC-BY-4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    references: [
      {
        id: "witten2022crossed",
        authors: "Witten E.",
        year: 2022,
        title: "Gravity and the crossed product",
        venue: "JHEP 2022(10), 008",
        arxiv: "2112.12828",
      },
      {
        id: "chandrasekaran2022clpw",
        authors: "Chandrasekaran V., Longo R., Penington G., Witten E.",
        year: 2023,
        title: "An algebra of observables for de Sitter space",
        venue: "JHEP 2023(2), 082",
        arxiv: "2206.10780",
      },
      {
        id: "bao2015hec",
        authors: "Bao N., Nezami S., Ooguri H., Stoica B., Sully J., Walter M.",
        year: 2015,
        title: "The holographic entropy cone",
        venue: "JHEP 2015(9), 130",
        arxiv: "1505.07839",
      },
      {
        id: "cohenkaplannelson1999",
        authors: "Cohen A. G., Kaplan D. B., Nelson A. E.",
        year: 1999,
        title: "Effective field theory, black holes, and the cosmological constant",
        venue: "Physical Review Letters 82, 4971",
        arxiv: "hep-th/9803132",
      },
      {
        id: "page1983wootters",
        authors: "Page D. N., Wootters W. K.",
        year: 1983,
        title: "Evolution without evolution: dynamics described by stationary observables",
        venue: "Physical Review D 27, 2885",
      },
      {
        id: "verlinde2011origin",
        authors: "Verlinde E.",
        year: 2011,
        title: "On the origin of gravity and the laws of Newton",
        venue: "Journal of High Energy Physics 2011(4), 29",
        doi: "10.1007/JHEP04(2011)029",
      },
      {
        id: "verlinde2017emergent",
        authors: "Verlinde E.",
        year: 2017,
        title: "Emergent gravity and the dark universe",
        venue: "SciPost Physics 2(3), 016",
        doi: "10.21468/SciPostPhys.2.3.016",
      },
      {
        id: "vanchurin2020world",
        authors: "Vanchurin V.",
        year: 2020,
        title: "The world as a neural network",
        venue: "Entropy 22(11), 1210",
        doi: "10.3390/e22111210",
      },
      {
        id: "wolfram2020project",
        authors: "Wolfram S.",
        year: 2020,
        title: "A class of models with the potential to represent fundamental physics",
        venue: "Complex Systems 29(2), 107",
      },
      {
        id: "gorard2020some",
        authors: "Gorard J.",
        year: 2020,
        title: "Some relativistic and gravitational properties of the Wolfram model",
        venue: "arXiv",
        arxiv: "2004.14810",
      },
      {
        id: "tononi2004iit",
        authors: "Tononi G.",
        year: 2004,
        title: "An information integration theory of consciousness",
        venue: "BMC Neuroscience 5, 42",
        doi: "10.1186/1471-2202-5-42",
      },
      {
        id: "tononi2008",
        authors: "Tononi G.",
        year: 2008,
        title: "Consciousness as integrated information",
        venue: "Biological Bulletin 215, 216",
        doi: "10.2307/25470707",
      },
      {
        id: "penrose1996orchestrated",
        authors: "Penrose R., Hameroff S.",
        year: 1996,
        title: "Orchestrated reduction of quantum coherence in brain microtubules",
        venue: "Mathematics and Computers in Simulation 40, 453",
        doi: "10.1016/0378-4754(96)80476-9",
      },
      {
        id: "chalmers1995facing",
        authors: "Chalmers D. J.",
        year: 1995,
        title: "Facing up to the problem of consciousness",
        venue: "Journal of Consciousness Studies 2(3), 200",
      },
      {
        id: "dehaene2003",
        authors: "Dehaene S., Sergent C., Changeux J.-P.",
        year: 2003,
        title: "A neuronal network model linking subjective reports and objective physiological data",
        venue: "PNAS 100(14), 8520",
        doi: "10.1073/pnas.1332574100",
      },
      {
        id: "baars1988cognitive",
        authors: "Baars B. J.",
        year: 1988,
        title: "A Cognitive Theory of Consciousness",
        venue: "Cambridge University Press",
      },
      {
        id: "libet1983time",
        authors: "Libet B.",
        year: 1983,
        title: "Time of conscious intention to act in relation to onset of cerebral activity",
        venue: "Brain 106(3), 623",
        doi: "10.1093/brain/106.3.623",
      },
      {
        id: "rosenthal2005",
        authors: "Rosenthal D. M.",
        year: 2005,
        title: "Consciousness and Mind",
        venue: "Oxford University Press",
      },
      {
        id: "miller1956magical",
        authors: "Miller G. A.",
        year: 1956,
        title: "The magical number seven, plus or minus two",
        venue: "Psychological Review 63, 81",
        doi: "10.1037/h0043158",
      },
      {
        id: "wheeler1990information",
        authors: "Wheeler J. A.",
        year: 1990,
        title: "Information, physics, quantum: the search for links",
        venue: "Complexity, Entropy, and the Physics of Information (Addison-Wesley)",
      },
      {
        id: "bekenstein1973black",
        authors: "Bekenstein J. D.",
        year: 1973,
        title: "Black holes and entropy",
        venue: "Physical Review D 7(8), 2333",
        doi: "10.1103/PhysRevD.7.2333",
      },
      {
        id: "susskind1995world",
        authors: "Susskind L.",
        year: 1995,
        title: "The world as a hologram",
        venue: "Journal of Mathematical Physics 36, 6377",
        doi: "10.1063/1.531249",
      },
      {
        id: "thooft1993dimensional",
        authors: "'t Hooft G.",
        year: 1993,
        title: "Dimensional reduction in quantum gravity",
        venue: "arXiv",
        arxiv: "gr-qc/9310026",
      },
      {
        id: "maldacena2013cool",
        authors: "Maldacena J., Susskind L.",
        year: 2013,
        title: "Cool horizons for entangled black holes",
        venue: "Fortschritte der Physik 61, 781",
        doi: "10.1002/prop.201300020",
      },
      {
        id: "page1993information",
        authors: "Page D. N.",
        year: 1993,
        title: "Information in black-hole radiation",
        venue: "Physical Review Letters 71, 3743",
        doi: "10.1103/PhysRevLett.71.3743",
      },
      {
        id: "godel1931formally",
        authors: "Gödel K.",
        year: 1931,
        title: "Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme I",
        venue: "Monatshefte für Mathematik und Physik 38, 173",
      },
      {
        id: "turing1936computable",
        authors: "Turing A. M.",
        year: 1936,
        title: "On computable numbers, with an application to the Entscheidungsproblem",
        venue: "Proc. London Math. Soc. 42, 230",
      },
      {
        id: "chaitin1975theory",
        authors: "Chaitin G. J.",
        year: 1975,
        title: "A theory of program size formally identical to information theory",
        venue: "Journal of the ACM 22(3), 329",
        doi: "10.1145/321892.321894",
      },
      {
        id: "kung1981optimistic",
        authors: "Kung H. T., Robinson J. T.",
        year: 1981,
        title: "On optimistic methods for concurrency control",
        venue: "ACM Transactions on Database Systems 6(2), 213",
        doi: "10.1145/319566.319567",
      },
    ],
  },
];

export function getPaperBySlug(slug: string): Paper | undefined {
  return papers.find((p) => p.slug === slug);
}
